In [1]:
from glob import glob
import json
import pandas as pd
import numpy as np
from IPython.display import display_html

In [2]:
results = [json.load(open(f)) for f in glob("set_rank_results_cifar10/*.json")]
results = pd.DataFrame(results)

results["best_loss"] = results["loss"].map(np.min)
results["best_loss_epoch"] = results["loss"].map(lambda x: np.argmin(x) + 1)
results["best_categorical_accuracy"] = results["categorical_accuracy"].map(np.max)
results["best_categorical_accuracy_epoch"] = results["categorical_accuracy"].map(lambda x: np.argmax(x) + 1)
results["best_val_loss"] = results["val_loss"].map(np.min)
results["best_val_loss_epoch"] = results["val_loss"].map(lambda x: np.argmin(x) + 1)
results["best_val_categorical_accuracy"] = results["val_categorical_accuracy"].map(np.max)
results["best_val_categorical_accuracy_epoch"] = results["val_categorical_accuracy"].map(lambda x: np.argmax(x) + 1)
results["initial_rank"].replace(-1, 256, inplace=True)
results["new_rank"].replace(-1, 256, inplace=True)
results.head()

initial_rank  new_rank  rank_update_epoch  total_epochs  \
0           200         1                 25            50   
1             1       200                 25            50   
2             4         4                  1            50   
3            53       200                  2            50   
4           256         1                  5            50   

                                                loss  \
0  [1.6945616006851196, 1.3467351198196411, 1.185...   
1  [1.9884175062179565, 1.8690537214279175, 1.842...   
2  [1.8733692169189453, 1.5795079469680786, 1.467...   
3  [1.703080177307129, 1.3980000019073486, 1.2670...   
4  [1.7061458826065063, 1.3607358932495117, 1.217...   

                                categorical_accuracy  \
0  [0.3723999857902527, 0.5099200010299683, 0.574...   
1  [0.17518000304698944, 0.2015399932861328, 0.20...   
2  [0.2890799939632416, 0.398140013217926, 0.4439...   
3  [0.3668400049209595, 0.48848000168800354, 0.53...   
4  [0.3745200037956238, 0.5076599717140198, 0.566...   

                                            val_loss  \
0  [1.4748198986053467, 1.2428358793258667, 1.185...   
1  [1.8942424058914185, 1.8421685695648193, 1.835...   
2  [1.6671442985534668, 1.5272045135498047, 1.487...   
3  [1.5254783630371094, 1.3288847208023071, 1.187...   
4  [1.4480233192443848, 1.241896390914917, 1.1797...   

                            val_categorical_accuracy  pre_update_loss  \
0  [0.45649999380111694, 0.5493000149726868, 0.57...         0.101661   
1  [0.19429999589920044, 0.20469999313354492, 0.2...         1.119931   
2  [0.36809998750686646, 0.4235000014305115, 0.43...         1.670200   
3  [0.4300999939441681, 0.5163999795913696, 0.573...         1.328509   
4  [0.48159998655319214, 0.5575000047683716, 0.58...         1.060793   

   pre_update_categorical_accuracy  ...  post_update_val_loss  \
0                          0.96734  ...              2.106575   
1                          0.53476  ...              1.503841   
2                          0.36016  ...              1.667161   
3                          0.51318  ...              1.328893   
4                          0.62576  ...              2.129262   

   post_update_val_categorical_accuracy  best_loss  best_loss_epoch  \
0                                0.1830   0.125470               25   
1                                0.4341   0.086989               49   
2                                0.3680   0.068136               50   
3                                0.5163   0.024365               49   
4                                0.1699   0.643196               50   

   best_categorical_accuracy  best_categorical_accuracy_epoch  best_val_loss  \
0                    0.95858                               25       0.695949   
1                    0.97082                               49       0.995005   
2                    0.97778                               50       0.814334   
3                    0.99210                               49       0.705702   
4                    0.74418                               50       1.075168   

   best_val_loss_epoch  best_val_categorical_accuracy  \
0                   17                         0.7775   
1                   33                         0.7267   
2                   27                         0.7295   
3                   18                         0.7741   
4                    4                         0.6241   

   best_val_categorical_accuracy_epoch  
0                                   24  
1                                   50  
2                                   33  
3                                   50  
4                                    4  

[5 rows x 24 columns]

In [3]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3844 entries, 0 to 3843
Data columns (total 24 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   initial_rank                          3844 non-null   int64  
 1   new_rank                              3844 non-null   int64  
 2   rank_update_epoch                     3844 non-null   int64  
 3   total_epochs                          3844 non-null   int64  
 4   loss                                  3844 non-null   object 
 5   categorical_accuracy                  3844 non-null   object 
 6   val_loss                              3844 non-null   object 
 7   val_categorical_accuracy              3844 non-null   object 
 8   pre_update_loss                       3844 non-null   float64
 9   pre_update_categorical_accuracy       3844 non-null   float64
 10  pre_update_val_loss                   3844 non-null   float64
 11  pre_update_val_ca

In [4]:
np.argmax(results["best_val_categorical_accuracy"])

1098

In [5]:
results.iloc[55]

initial_rank                                                                           14
new_rank                                                                              200
rank_update_epoch                                                                      10
total_epochs                                                                           50
loss                                    [1.8028253316879272, 1.4960806369781494, 1.363...
categorical_accuracy                    [0.3247399926185608, 0.4496400058269501, 0.503...
val_loss                                [1.569806694984436, 1.43424654006958, 1.282783...
val_categorical_accuracy                [0.41990000009536743, 0.47909998893737793, 0.5...
pre_update_loss                                                                  0.848009
pre_update_categorical_accuracy                                                    0.7043
pre_update_val_loss                                                              0.910688
pre_update

In [6]:
display(results["initial_rank"].unique())
display(results["new_rank"].unique())
display(results["rank_update_epoch"].unique())

array([200,   1,   4,  53, 256,  14])

array([  1, 200,   4, 256,  53,  14])

array([25,  1,  2,  5, 10])

In [7]:
len(results)

3844

In [8]:
def visualize(column: str, rank_update_epoch: int):
    avg_results = pd.pivot_table(
        results.loc[
            results["rank_update_epoch"] == rank_update_epoch,
            ["initial_rank", "new_rank", column]
        ],
        index="initial_rank",
        columns="new_rank",
    )
    count_results = pd.pivot_table(
        results.loc[
            results["rank_update_epoch"] == rank_update_epoch,
            ["initial_rank", "new_rank", column]
        ],
        index="initial_rank",
        columns="new_rank",
        fill_value=0,
        aggfunc=len
    )
    display_html(
        avg_results
            .style
            .background_gradient(cmap='Blues', axis=None, vmin=0.77)
            .format("{:.3f}")
            .set_table_attributes("style='display:inline'")
            .set_caption("Avg")
            .set_properties(width="40px", height="40px")
            ._repr_html_() + \
        count_results
            .style
            .background_gradient(cmap='Blues', axis=None)
            .format("{:.0f}")
            .set_table_attributes("style='display:inline'")
            .set_caption("Count")
            .set_properties(width="40px", height="40px")
            ._repr_html_(),
        raw=True
    )

In [9]:
for rank_update_epoch in np.sort(results["rank_update_epoch"].unique()):
    print(f"Rank updated on epoch: {rank_update_epoch}")
    visualize("best_val_categorical_accuracy", rank_update_epoch)

Rank updated on epoch: 1


Avg 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 0.457 
 0.716 
 0.744 
 0.760 
 0.771 
 0.781 
 
 
 4 
 0.464 
 0.734 
 0.766 
 0.775 
 0.777 
 0.779 
 
 
 14 
 0.460 
 0.735 
 0.781 
 0.777 
 0.776 
 0.780 
 
 
 53 
 0.470 
 0.736 
 0.778 
 0.780 
 0.778 
 0.778 
 
 
 200 
 0.474 
 0.737 
 0.780 
 0.781 
 0.779 
 0.782 
 
 
 256 
 0.473 
 0.739 
 0.780 
 0.779 
 0.777 
 0.780 
 
 
 

 
 Count 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 25 
 28 
 16 
 16 
 14 
 27 
 
 
 4 
 18 
 25 
 21 
 16 
 22 
 19 
 
 
 14 
 16 
 23 
 21 
 25 
 25 
 19 
 
 
 53 
 16 
 16 
 21 
 19 
 27 
 22 
 
 
 200 
 21 
 18 
 13 
 17 
 20 
 29 
 
 
 256 
 18 
 23 
 23 
 20 
 23 
 23

Rank updated on epoch: 2


Avg 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 0.456 
 0.716 
 0.744 
 0.759 
 0.769 
 0.781 
 
 
 4 
 0.466 
 0.733 
 0.769 
 0.776 
 0.777 
 0.780 
 
 
 14 
 0.482 
 0.737 
 0.781 
 0.779 
 0.777 
 0.780 
 
 
 53 
 0.511 
 0.736 
 0.779 
 0.778 
 0.778 
 0.779 
 
 
 200 
 0.546 
 0.737 
 0.779 
 0.780 
 0.776 
 0.781 
 
 
 256 
 0.535 
 0.737 
 0.778 
 0.778 
 0.776 
 0.780 
 
 
 

 
 Count 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 20 
 15 
 18 
 19 
 26 
 24 
 
 
 4 
 15 
 28 
 11 
 23 
 24 
 17 
 
 
 14 
 17 
 21 
 14 
 23 
 26 
 17 
 
 
 53 
 18 
 16 
 18 
 16 
 27 
 34 
 
 
 200 
 21 
 23 
 17 
 26 
 24 
 19 
 
 
 256 
 20 
 29 
 17 
 22 
 19 
 19

Rank updated on epoch: 5


Avg 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 0.454 
 0.712 
 0.743 
 0.757 
 0.768 
 0.780 
 
 
 4 
 0.532 
 0.732 
 0.768 
 0.777 
 0.777 
 0.779 
 
 
 14 
 0.585 
 0.736 
 0.779 
 0.778 
 0.777 
 0.781 
 
 
 53 
 0.625 
 0.737 
 0.779 
 0.779 
 0.778 
 0.782 
 
 
 200 
 0.652 
 0.737 
 0.780 
 0.779 
 0.781 
 0.783 
 
 
 256 
 0.640 
 0.740 
 0.778 
 0.778 
 0.777 
 0.780 
 
 
 

 
 Count 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 21 
 16 
 22 
 18 
 24 
 17 
 
 
 4 
 18 
 21 
 25 
 22 
 22 
 21 
 
 
 14 
 21 
 20 
 21 
 31 
 19 
 16 
 
 
 53 
 31 
 30 
 22 
 23 
 28 
 27 
 
 
 200 
 18 
 17 
 20 
 28 
 19 
 26 
 
 
 256 
 21 
 20 
 33 
 19 
 16 
 22

Rank updated on epoch: 10


Avg 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 0.451 
 0.708 
 0.734 
 0.753 
 0.766 
 0.776 
 
 
 4 
 0.619 
 0.734 
 0.765 
 0.774 
 0.777 
 0.779 
 
 
 14 
 0.679 
 0.741 
 0.779 
 0.779 
 0.779 
 0.784 
 
 
 53 
 0.703 
 0.743 
 0.778 
 0.778 
 0.780 
 0.780 
 
 
 200 
 0.732 
 0.745 
 0.781 
 0.779 
 0.779 
 0.782 
 
 
 256 
 0.714 
 0.743 
 0.779 
 0.778 
 0.780 
 0.780 
 
 
 

 
 Count 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 19 
 18 
 18 
 18 
 20 
 22 
 
 
 4 
 25 
 23 
 25 
 29 
 21 
 19 
 
 
 14 
 27 
 22 
 19 
 24 
 26 
 26 
 
 
 53 
 21 
 17 
 21 
 11 
 19 
 20 
 
 
 200 
 21 
 15 
 20 
 24 
 19 
 29 
 
 
 256 
 18 
 23 
 16 
 19 
 18 
 26

Rank updated on epoch: 25


Avg 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 0.452 
 0.648 
 0.679 
 0.702 
 0.721 
 0.723 
 
 
 4 
 0.718 
 0.734 
 0.748 
 0.756 
 0.762 
 0.760 
 
 
 14 
 0.767 
 0.767 
 0.780 
 0.779 
 0.779 
 0.779 
 
 
 53 
 0.774 
 0.774 
 0.778 
 0.780 
 0.781 
 0.781 
 
 
 200 
 0.775 
 0.777 
 0.782 
 0.782 
 0.782 
 0.782 
 
 
 256 
 0.773 
 0.774 
 0.779 
 0.779 
 0.778 
 0.780 
 
 
 

 
 Count 
 
 
   
 best_val_categorical_accuracy 
 
 
 new_rank 
 1 
 4 
 14 
 53 
 200 
 256 
 
 
 initial_rank 
   
   
   
   
   
   
 
 
 
 
 1 
 18 
 23 
 26 
 19 
 27 
 30 
 
 
 4 
 21 
 26 
 16 
 27 
 22 
 17 
 
 
 14 
 24 
 25 
 21 
 21 
 19 
 16 
 
 
 53 
 19 
 20 
 26 
 27 
 19 
 20 
 
 
 200 
 20 
 28 
 19 
 30 
 20 
 32 
 
 
 256 
 21 
 18 
 18 
 25 
 19 
 24