In [1]:
from glob import glob
import json
import pandas as pd
import numpy as np

In [2]:
results = [json.load(open(f)) for f in glob("set_rank_results_cifar10/*.json")]
results = pd.DataFrame(results)

results["best_loss"] = results["loss"].map(np.min)
results["best_loss_epoch"] = results["loss"].map(lambda x: np.argmin(x) + 1)
results["best_categorical_accuracy"] = results["categorical_accuracy"].map(np.max)
results["best_categorical_accuracy_epoch"] = results["categorical_accuracy"].map(lambda x: np.argmax(x) + 1)
results["best_val_loss"] = results["val_loss"].map(np.min)
results["best_val_loss_epoch"] = results["val_loss"].map(lambda x: np.argmin(x) + 1)
results["best_val_categorical_accuracy"] = results["val_categorical_accuracy"].map(np.max)
results["best_val_categorical_accuracy_epoch"] = results["val_categorical_accuracy"].map(lambda x: np.argmax(x) + 1)
results["initial_rank"].replace(-1, 256, inplace=True)
results["new_rank"].replace(-1, 256, inplace=True)
results.head()

initial_rank  new_rank  rank_update_epoch  total_epochs  \
0           200        14                 10            50   
1           256        53                 25            50   
2             1        14                  2            50   
3           256        53                 25            50   
4            53       256                  5            50   

                                                loss  \
0  [1.6943475008010864, 1.3511114120483398, 1.194...   
1  [1.6889116764068604, 1.363222360610962, 1.2238...   
2  [2.008345365524292, 1.8717670440673828, 1.6404...   
3  [1.6964704990386963, 1.3796123266220093, 1.238...   
4  [1.7248677015304565, 1.4034148454666138, 1.257...   

                                categorical_accuracy  \
0  [0.37577998638153076, 0.5093200206756592, 0.57...   
1  [0.37882000207901, 0.5082399845123291, 0.56260...   
2  [0.1775200068950653, 0.2021999955177307, 0.358...   
3  [0.38141998648643494, 0.49987998604774475, 0.5...   
4  [0.36037999391555786, 0.48594000935554504, 0.5...   

                                            val_loss  \
0  [1.4911612272262573, 1.366654396057129, 1.1663...   
1  [1.4815499782562256, 1.3108307123184204, 1.184...   
2  [1.8917927742004395, 1.8449923992156982, 1.522...   
3  [1.479851484298706, 1.2734463214874268, 1.1835...   
4  [1.5207701921463013, 1.323439598083496, 1.1983...   

                            val_categorical_accuracy  pre_update_loss  \
0  [0.4528999924659729, 0.5027999877929688, 0.573...         0.731901   
1  [0.47040000557899475, 0.5213000178337097, 0.57...         0.225114   
2  [0.19269999861717224, 0.20659999549388885, 0.4...         1.846736   
3  [0.45910000801086426, 0.5455999970436096, 0.57...         0.283592   
4  [0.43720000982284546, 0.517300009727478, 0.566...         1.010023   

   pre_update_categorical_accuracy  ...  post_update_val_loss  \
0                          0.74680  ...              0.864800   
1                          0.92738  ...              0.784675   
2                          0.20748  ...              1.844984   
3                          0.90522  ...              0.733720   
4                          0.63942  ...              1.039510   

   post_update_val_categorical_accuracy  best_loss  best_loss_epoch  \
0                                0.7045   0.009646               50   
1                                0.7653   0.019536               46   
2                                0.2063   0.068689               50   
3                                0.7678   0.025703               49   
4                                0.6325   0.009879               49   

   best_categorical_accuracy  best_categorical_accuracy_epoch  best_val_loss  \
0                    0.99772                               50       0.702425   
1                    0.99490                               46       0.705935   
2                    0.97712                               50       0.814391   
3                    0.99254                               49       0.686433   
4                    0.99844                               49       0.672208   

   best_val_loss_epoch  best_val_categorical_accuracy  \
0                   16                         0.7842   
1                   19                         0.7748   
2                   25                         0.7440   
3                   21                         0.7781   
4                   20                         0.7818   

   best_val_categorical_accuracy_epoch  
0                                   50  
1                                   50  
2                                   30  
3                                   32  
4                                   25  

[5 rows x 24 columns]

In [3]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114 entries, 0 to 113
Data columns (total 24 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   initial_rank                          114 non-null    int64  
 1   new_rank                              114 non-null    int64  
 2   rank_update_epoch                     114 non-null    int64  
 3   total_epochs                          114 non-null    int64  
 4   loss                                  114 non-null    object 
 5   categorical_accuracy                  114 non-null    object 
 6   val_loss                              114 non-null    object 
 7   val_categorical_accuracy              114 non-null    object 
 8   pre_update_loss                       114 non-null    float64
 9   pre_update_categorical_accuracy       114 non-null    float64
 10  pre_update_val_loss                   114 non-null    float64
 11  pre_update_val_cate

In [4]:
np.argmax(results["best_val_categorical_accuracy"])

29

In [5]:
results.iloc[29]

initial_rank                                                                          256
new_rank                                                                              256
rank_update_epoch                                                                       1
total_epochs                                                                           50
loss                                    [1.696595311164856, 1.3655939102172852, 1.2236...
categorical_accuracy                    [0.3770799934864044, 0.505020022392273, 0.5625...
val_loss                                [1.4686557054519653, 1.2875036001205444, 1.172...
val_categorical_accuracy                [0.4708000123500824, 0.5331000089645386, 0.579...
pre_update_loss                                                                  1.472105
pre_update_categorical_accuracy                                                   0.47014
pre_update_val_loss                                                              1.468609
pre_update

In [6]:
display(results["initial_rank"].unique())
display(results["new_rank"].unique())
display(results["rank_update_epoch"].unique())

array([200, 256,   1,  53,   4,  14])

array([ 14,  53, 256,   1,   4, 200])

array([10, 25,  2,  5,  1])

In [7]:
def visualize(column: str, rank_update_epoch: int):
    avg_results = pd.pivot_table(
        results.loc[
            results["rank_update_epoch"] == rank_update_epoch,
            ["initial_rank", "new_rank", column]
        ],
        index="initial_rank",
        columns="new_rank",
    )
    display(
        avg_results
            .style
            .background_gradient(cmap='Blues')
            .format("{:.3f}")
    )

In [8]:
for rank_update_epoch in np.sort(results["rank_update_epoch"].unique()):
    print(f"Rank updated on epoch: {rank_update_epoch}")
    visualize("best_val_categorical_accuracy", rank_update_epoch)

Rank updated on epoch: 1


Rank updated on epoch: 2


Rank updated on epoch: 5


Rank updated on epoch: 10


Rank updated on epoch: 25
