In [1]:
from glob import glob
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib notebook
plt.ioff()

In [2]:
results = [json.load(open(f)) for f in glob("set_rank_results_cifar10/*.json")]
results = pd.DataFrame(results)
def get_epoch(x):
    return np.argmax(x) + 1

results["best_loss"] = results["loss"].map(np.min)
results["best_loss_epoch"] = results["loss"].map(get_epoch)
results["best_categorical_accuracy"] = results["categorical_accuracy"].map(np.max)
results["best_categorical_accuracy_epoch"] = results["categorical_accuracy"].map(get_epoch)
results["best_val_loss"] = results["val_loss"].map(np.min)
results["best_val_loss_epoch"] = results["val_loss"].map(get_epoch)
results["best_val_categorical_accuracy"] = results["val_categorical_accuracy"].map(np.max)
results["best_val_categorical_accuracy_epoch"] = results["val_categorical_accuracy"].map(get_epoch)
results["initial_rank"].replace(-1, 256, inplace=True)
results["new_rank"].replace(-1, 256, inplace=True)
results.head()

initial_rank  new_rank  rank_update_epoch  total_epochs  pre_update_loss  \
0           256       256                  0            50         2.303892   
1           256        10                  0            50         2.303252   
2           256        10                  1            50         1.499016   
3           256        10                  2            50         1.266334   
4           256        10                  3            50         1.170079   

   pre_update_categorical_accuracy  pre_update_val_loss  \
0                          0.10328             2.303917   
1                          0.09582             2.303138   
2                          0.45636             1.492432   
3                          0.54004             1.268022   
4                          0.58624             1.176452   

   pre_update_val_categorical_accuracy  post_update_loss  \
0                               0.1040          2.303892   
1                               0.0971          2.303252   
2                               0.4582          1.499016   
3                               0.5372          1.266334   
4                               0.5812          1.170079   

   post_update_categorical_accuracy  ...  \
0                           0.10328  ...   
1                           0.09582  ...   
2                           0.45636  ...   
3                           0.54004  ...   
4                           0.58624  ...   

                                            val_loss  \
0  [1.4626364707946777, 1.260942816734314, 1.1707...   
1  [2.1047847270965576, 2.0721733570098877, 1.989...   
2  [1.4924323558807373, 1.2711848020553589, 1.155...   
3  [1.4505895376205444, 1.268022060394287, 1.1844...   
4  [1.466644287109375, 1.2580969333648682, 1.1764...   

                            val_categorical_accuracy best_loss  \
0  [0.4569999873638153, 0.5432999730110168, 0.578...  0.019316   
1  [0.17249999940395355, 0.17649999260902405, 0.1...  0.044516   
2  [0.45820000767707825, 0.5422999858856201, 0.58...  0.017307   
3  [0.46619999408721924, 0.5371999740600586, 0.57...  0.018660   
4  [0.4641000032424927, 0.5473999977111816, 0.581...  0.016716   

  best_loss_epoch best_categorical_accuracy best_categorical_accuracy_epoch  \
0               1                   0.99488                              48   
1               1                   0.98732                              49   
2               1                   0.99600                              50   
3               1                   0.99520                              48   
4               1                   0.99588                              48   

   best_val_loss  best_val_loss_epoch  best_val_categorical_accuracy  \
0       0.695018                    1                         0.7780   
1       1.490433                    1                         0.5094   
2       0.699587                    1                         0.7723   
3       0.701269                    1                         0.7762   
4       0.693571                   48                         0.7792   

   best_val_categorical_accuracy_epoch  
0                                   29  
1                                   32  
2                                   36  
3                                   34  
4                                   34  

[5 rows x 24 columns]

In [3]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 24 columns):
 #   Column                                Non-Null Count  Dtype  
---  ------                                --------------  -----  
 0   initial_rank                          126 non-null    int64  
 1   new_rank                              126 non-null    int64  
 2   rank_update_epoch                     126 non-null    int64  
 3   total_epochs                          126 non-null    int64  
 4   pre_update_loss                       126 non-null    float64
 5   pre_update_categorical_accuracy       126 non-null    float64
 6   pre_update_val_loss                   126 non-null    float64
 7   pre_update_val_categorical_accuracy   126 non-null    float64
 8   post_update_loss                      126 non-null    float64
 9   post_update_categorical_accuracy      126 non-null    float64
 10  post_update_val_loss                  126 non-null    float64
 11  post_update_val_cat

In [4]:
np.argmax(results["best_val_categorical_accuracy"])

28

In [5]:
results.iloc[28]

initial_rank                                                                           10
new_rank                                                                              160
rank_update_epoch                                                                       2
total_epochs                                                                           50
pre_update_loss                                                                  1.423933
pre_update_categorical_accuracy                                                   0.48032
pre_update_val_loss                                                              1.427604
pre_update_val_categorical_accuracy                                                0.4795
post_update_loss                                                                 1.423933
post_update_categorical_accuracy                                                  0.48032
post_update_val_loss                                                             1.427604
post_updat

In [6]:
display(results["initial_rank"].unique())
display(results["new_rank"].unique())
display(results["rank_update_epoch"].unique())

array([256,  10, 160,   1,   5,  60], dtype=int64)

array([256,  10, 160,   1,   5,  60], dtype=int64)

array([0, 1, 2, 3], dtype=int64)

In [7]:
def plottable_3d_info(df: pd.DataFrame):
    index = df.index
    columns = df.columns
    x, y = np.meshgrid(np.arange(len(columns)), np.arange(len(index)))
    z = np.array([[df[c][i] for c in columns] for i in index])
    x_ticks = dict(ticks=np.arange(len(columns)), labels=columns)
    y_ticks = dict(ticks=np.arange(len(index)), labels=index)
    return x, y, z, x_ticks, y_ticks

In [8]:
def wireframe_plot(r, z_str):
    x, y, z, x_ticks, y_ticks = plottable_3d_info(r)
    fig = plt.figure()
    axes = fig.add_subplot(projection="3d")
    axes.plot_wireframe(x, y, z)
    axes.set_xlabel('New Rank')
    axes.set_ylabel('Rank Update Epoch')
    axes.set_zlabel(z_str)
    axes.set_zlim3d(bottom=0)
    plt.xticks(**x_ticks)
    plt.yticks(**y_ticks)
    plt.show()

def rank_update_analysis(initial_rank: int):
    r = pd.pivot(
        results[results["initial_rank"] == initial_rank],
        index="rank_update_epoch",
        columns="new_rank")
    wireframe_plot(r["best_val_loss"], "Best Val Loss")
    wireframe_plot(r["best_val_loss_epoch"], "Best Val Epoch")

rank_update_analysis(160)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [9]:
def rank_update_epoch_analysis(initial_rank: int, new_rank: int):
    r = results.loc[(results["initial_rank"] == initial_rank) & (results["new_rank"] == new_rank)]
    r.groupby("rank_update_epoch").first()  # we should only have one run for each config

    plt.xlabel("Rank Update Epoch")
    plt.ylabel("Val Loss")
    plt.plot(r["rank_update_epoch"], r["best_val_loss"])
    plt.show()

    plt.xlabel("Rank Update Epoch")
    plt.ylabel("Best Val Loss Epoch")
    plt.plot(r["rank_update_epoch"], r["best_val_loss_epoch"])
    plt.show()
rank_update_epoch_analysis(160, 10)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [10]:
def new_rank_analysis(initial_rank: int, rank_update_epoch: int):
    r = results.loc[(results["initial_rank"] == initial_rank) & (results["rank_update_epoch"] == rank_update_epoch)]
    r.groupby("rank_update_epoch").first()  # we should only have one run for each config

    plt.xlabel("New Rank")
    plt.ylabel("Val Loss")
    plt.plot(r["new_rank"], r["best_val_loss"])
    plt.show()

    plt.xlabel("New Rank")
    plt.ylabel("Best Val Loss Epoch")
    plt.plot(r["new_rank"], r["best_val_loss_epoch"])
    plt.show()
new_rank_analysis(160, 1)

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>